#!/usr/bin/env sh

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

ln -sf $DOTFILES/zsh/zshrc $HOME/.zshrc

# ln -sf $DOTFILES/.vscode/settings.json $HOME/Library/Application\ Support/Code/User/settings.json
